tap "mongodb/brew"
brew "awscli"
brew "bash-completion"
brew "libpq", link: true
brew "nss"
brew "gh"
brew "git"
brew "go"
brew "mkcert"
brew "postgis"
brew "postgresql@16", restart_service: :changed
brew "redis", restart_service: :changed
brew "titlecase"
brew "tmux"
brew "mongodb/brew/mongodb-community@8.0"
# GUI Apps
cask "1password"
cask "brave-browser"
cask "caffeine"
cask "charles"
cask "claude"
cask "claude-code"
cask "cursor"
cask "discord"
cask "docker"
cask "home-assistant"
cask "jellyfin"
cask "signal"
cask "slack"
cask "spotify"
cask "tailscale"
cask "ticktick"
cask "vlc"
cask "whatsapp"
cask "zoom"
